/run/numberOfThreads 4

/control/verbose 2
/run/verbose 2

/Geometry/add LaBr1Detector
/Geometry/add LaBr2Detector
/Geometry/add TargetChamber

/Geometry/LaBr1Detector/position 0 0 ddd cm
/Geometry/LaBr2Detector/position 0 0 -ddd cm
/Geometry/TargetChamber/position 0 -8 0 cm

/Geometry/TargetChamber/rotateX 90 deg
/Geometry/TargetChamber/rotateZ 180 deg
/Geometry/LaBr2Detector/rotateY 180 deg

/run/initialize

/PrimaryGenerator/select NuclideGun
/PrimaryGenerator/NuclideGun/mass 137
/PrimaryGenerator/NuclideGun/charge 55
/PrimaryGenerator/NuclideGun/position xxx yyy zzz cm

/run/setFileName 137Cs_dddcm.root

/run/beamOn 1000000
