/run/numberOfThreads 4

/control/verbose 2
/run/verbose 2

/Geometry/add LaBrDetector
/Geometry/LaBrDetector/position 0 0 0 cm

/PrimaryGenerator/select GammaDecayScheme
/PrimaryGenerator/GammaDecayScheme/position 0 0 10 cm
/PrimaryGenerator/GammaDecayScheme/levelFile data/F18.txt
/PrimaryGenerator/GammaDecayScheme/excitedState 5673 keV

/run/setFileName sim.root

/run/initialize

/run/beamOn 1000000
