/run/numberOfThreads 4

/control/verbose 2
/control/saveHistory
/run/verbose 2

/Geometry/add LaBr1Detector
/Geometry/add LaBr2Detector

/Geometry/LaBr1Detector/position 0 0 0 cm
/Geometry/LaBr2Detector/position 0 0 -20 cm

/Geometry/LaBr2Detector/rotateY 180 deg

/PrimaryGenerator/select IsotropicGun
/PrimaryGenerator/IsotropicGun/position 0 0 -10 cm
/PrimaryGenerator/IsotropicGun/energy 1 MeV
/PrimaryGenerator/IsotropicGun/number 1

/run/setFileName vis.root

/run/initialize

/control/execute mac/vis.mac
