/run/numberOfThreads 4

/control/verbose 2
/control/saveHistory
/run/verbose 2

/Geometry/add LaBr1Detector
/Geometry/add LaBr2Detector
/Geometry/add TargetChamber

/Geometry/LaBr1Detector/position 0 0 10 cm
/Geometry/LaBr2Detector/position 0 0 -10 cm
/Geometry/TargetChamber/position 0 -8 0 cm

/Geometry/TargetChamber/rotateX 90 deg
/Geometry/TargetChamber/rotateZ 180 deg
/Geometry/LaBr2Detector/rotateY 180 deg

/run/initialize

/PrimaryGenerator/select IsotropicGun
/PrimaryGenerator/IsotropicGun/position 0 0 0 cm
/PrimaryGenerator/IsotropicGun/energy 1 MeV
/PrimaryGenerator/IsotropicGun/number 1

/run/setFileName temp.root

/control/execute mac/vis.mac
