/run/numberOfThreads 4

/control/verbose 2
/run/verbose 2

/Geometry/add LaBr1Detector
/Geometry/add LaBr2Detector

/Geometry/LaBr1Detector/position 0 0 0 cm
/Geometry/LaBr2Detector/position 0 0 -20 cm

/Geometry/LaBr2Detector/rotateY 180 deg

/PrimaryGenerator/select PositronGun
/PrimaryGenerator/PositronGun/file data/13N_decay.dat
/PrimaryGenerator/PositronGun/positon 0 0 -10 cm

/run/setFileName sim.root

/run/initialize

/run/beamOn 1000000
